### ISSUE TITLE
Migrating from SQL Server to PostgreSQL with COMB guids

### ISSUE THREAD

**Issue by kspearrin** [richardtallent/RT.Comb#10]
Hi,
Thanks for the awesome library. I don't necessarily have any issue with this library, but I was hoping your expertise on the matter would be able to help me.

I've been generating the SQL Server legacy COMB GUIDs for primary key values in a product for quite some time now (millions of records). We are currently evaluating the possibility of migrating the product from SQL Server to PostgreSQL and with this comes migrating all of the existing data.

My concern is that the existing comb GUIDs that were generated for SQL Server are of a different sort algorithm than what would have been for PostgreSQL. My guess is that generating new values under the PostgreSQL algorithm is not going to create the desired incremental GUID values based on the already existing IDs that would be migrated. New values would likely be somewhere in the middle of the index and will lead to fragmented tables.

Does that make sense?

Could you recommend any way of dealing with a situation like this? Perhaps there is some way I can seed the new PostgreSQL comb generator to always generate incremental GUIDs after the "last" (in terms of PostgreSQL sorting) one that was generated from the previous SQL Server legacy algorithm?

Thanks!

**Comment by richardtallent** [comment]
Hi Kevin,

I’m glad others are finding benefit from it! All of my open-source stuff is just a result of scratching my own itch.

You are correct -- PostgreSQL sorts UUIDs differently from SQL Server, so the bytes PostgreSQL wants to sort first will be random for the COMBs created previously in SQL Server. Since the old values are random, the "last" value won't provide a good high-water-mark you can use to bias new values.

A silver lining is that it may not make much difference. From a few minutes of research, my (very limited) understanding is that PostgreSQL doesn't guarantee to write new records into pages sequentially, and doesn't update them *in situ* either. Instead, updates and deletes free up the original record's space, and inserts and updates then reuse available space in whichever page is handy.

Some other thoughts:

1. You should evaluate, for each table, whether the PK *should* be the clustered key. If a table's UUID PK is rarely used in JOINs, it's likely that another column (or set of columns) will be a better choice for the clustered index. For example, in a traditional "products and orders" database, the "order line item" table for an order would be best clustered by the *order's* FK, not the line item's PK. That may not solve the problem for every table, but might help with joining tables especially.

2. It *is* possible to "convert" an SQL COMB to a PostgreSQL COMB deterministically, by swapping around the various random and time stamp byte ranges (and converting the time stamps to UNIX if you used the legacy DATETIME-based timestamp). That would mean changing every PK and FK reference, but would give you tables afterward that have sequential PKs across all time (and you'd be able to extract the timestamps reliably from both new and old values). Since you're transferring the data to a new platform anyway, it can be done during that transfer. You could set things up first in SQL Server, creating "sidecar" columns to temporarily store the PG-equivalent IDs while you plan the migration. Something like this:

```SQL
ALTER TABLE product ADD pgId UNIQUEIDENTIFIER NULL;
ALTER TABLE orderLineItem ADD pgId UNIQUEIDENTIFIER NULL, pgProductId UNIQUEIDENTIFIER NULL;

UPDATE product 
SET pgId = MyConvertFunction(id) 
WHERE pgId IS NULL;

UPDATE orderLineItem 
SET pgId = MyConvertFunction(id),
pgProductID = MyConvertFunction(productId)
WHERE pgId IS NULL;
```
This can be done in stages to prevent hitting your database too hard with the updates. Once you're ready to migrate, your migration script would look something a bit more like this:

```SQL
INSERT INTO [pgdb].product(id, ...)
SELECT pgId, ... FROM [mssqldb].product;

INSERT INTO [pgdb].orderLineItem(id, productId, ...)
SELECT pgId, pgProductId, ... FROM [mssqldb].orderLineItem;
```

Down side to this approach: if your database exposes the primary keys in ways that someone would want to refer to later (printed on records, bookmarked in browsers, data stores not managed by your database's referential integrity, etc.), changing UUID values would invalidate those old IDs. But it would be the "no compromise" solution. If bookmarked URLs are the issue, for *most* old UUIDs, you could "detect" the old value and redirect the user to the new value--just extract the timestamp, and if it's outside the window of dates your database has been around, it's an old UUID.

3. Even though I used COMBs on pretty much all tables these days, I also have a date/time of insertion field, because the COMB's timestamp value is unwieldy to query directly. If you do the same, another strategy would be to make the *clustered* index for your tables that date/time column, not the UUID PK. That would allow the records to be transferred in order and for future writes to be fairly sequential (see (1) above for the caveats), regardless how the new and old COMBs sort. Then you'd need another index on the UUID for lookups and joins. Granted, this means there's an additional level of "indirection" for queries on the UUID value (since it has to go through a regular index), but as with (1), any query performance impact might be negligible in real life, and at least it would less likely to write sequential records into different pages.

It's a bit late and this is sort of stream of consciousness, I hope it helps! I don't have the magic function described in (2) to convert from MSSQL-legacy COMBs to Postgre-Unix COMBs, but if you end up writing one, I'd be happy to accept a PR to add it to this library's utility functions.

**Comment by Mitch-Wheat** [comment]
https://pgxn.org/dist/sequential_uuids/1.0.1/
