### ISSUE TITLE
Create AspNetCore package

### ISSUE THREAD

**Issue by joaopgrassi** [richardtallent/RT.Comb#16]
Hey thanks for this library! I have been digging into this Comb Guid stuff lately and really liked the way this is implemented :)

Would be nice though to have a package in order to make it easier to add a comb provider to DI. Similar as the packages in ASP.NET Core (pay-to-play), we could have something like RT.Comb.AspNetCore. 

Since you are the owner, not sure if it makes sense to have someone else do the extension. I also saw it needs to be bumped to .NET Standard 2.0. If you need help with that I can jump in :).

**Comment by richardtallent** [comment]
Thanks! Yeah, it needed a little love on updating the dependencies, I've bumped it to 3.4.0 and published it, it is now built for .NET Standard 2.0, with the test and demo apps bumped to .NET Core 3.1.

I think a DI-specific version would be great, and I would appreciate the help!

I'm using it in an ASP.NET Core app now, but since I had a few "utility" singletons like this that are used in so many places and are *extremely* unlikely to be swapped out on the fly, I ended up creating a single "Site" singleton that carries them around as a group to reduce the number of arguments on my Controllers. Not exactly a "pure" approach to DI, but did the job.

**Comment by joaopgrassi** [comment]
Cool! So how would we go about doing the extension? I could do it under my name, but at least to me it always feels "sketchy" when the package on NuGet.org comes from someone else than the original author. So maybe you could create another Repo and then I could do the work :).

**Comment by richardtallent** [comment]
Hmm... this one repo already has the main package, demo app, and tests in the same repository, so the best option may just be to add another folder for the DI wrapper? Then I can just publish them separately to NuGet.

**Comment by joaopgrassi** [comment]
Well that sounds good as well. Didn't think on the obvious approach, sorry 😅. Great then I will see if I can get something done this week. Thanks!

**Comment by joaopgrassi** [comment]
I'll get the Hacktober fest inspiration and will be doing this in the following weeks. 😅
