### ISSUE TITLE
.NET Framework v4.6 is too restrictive

### ISSUE THREAD

**Issue by polewskm** [richardtallent/RT.Comb#3]
This library is great especially since it targets .NET Standard and .NET Framework but your latest version specifically targets **.NET Framework v4.6** which most people have not adopted yet. Would it be possible to lower the runtime version down to **v4.5.1**? It should be okay since you are not using anything specific from the newer runtime.

**Comment by richardtallent** [comment]
Sure thing. I'm working on a fix to the PostgreSql logic and reorganizing the code a bit to work better for DI, so there should be a new version available soon.

**Comment by richardtallent** [comment]
I finally had a chance to work on this a bit, fixing a logical issue in the PostgreSql implementation, upgrading to .NET Core 1.1 (just released), reorganizing the API, and as requested, moving back to 4.5.1. This was more difficult than I hoped because 4.6 has the ToUnixTimeMilliseconds / FromUnitTimeMilliseconds I wanted for a new variation. Please be sure to check out the new API, some changes will be needed.
